"""Guard the manuscript's generated formalism numbering.

Definitions and propositions used to carry hand-written numbers, and prose
referred to them the same way ("Proposition 6 pins this boundary"). Inserting a
block in the middle renumbered everything after it, and every reference to those
blocks kept pointing at the old number while the manuscript still rendered and
every gate stayed green.

Numbering is now generated by the renderer's formalism filter from labelled
fenced Divs, so three properties have to hold in the source and none of them is
visible to a reader of the rendered PDF:

1. every formalism block carries a well-formed, unique label;
2. every ``[@label]`` reference resolves to a block this manuscript declares —
   an unresolved one is reported on stderr by the filter and shipped as literal
   ``[@...]`` markup, with pandoc still exiting zero;
3. no manuscript file writes a block number by hand, anywhere outside a fenced
   code block.

Each checker below takes the manuscript as a mapping of filename to text, so the
same function that reads the real manuscript is run against planted violations.
A checker that has only ever seen the good manuscript is not evidence.
"""

from __future__ import annotations

import re
from pathlib import Path

MANUSCRIPT = Path(__file__).resolve().parent.parent / "manuscript"

#: The Div classes the shipped filter numbers, mapped to the label prefix this
#: manuscript requires for each. The filter accepts any prefix; the project does
#: not, because a consistent prefix is what makes a stale reference legible.
KIND_PREFIXES: dict[str, str] = {
    "definition": "def",
    "proposition": "prop",
    "theorem": "thm",
    "lemma": "lem",
    "corollary": "cor",
    "remark": "rem",
    "axiom": "ax",
    "claim": "clm",
    "example": "ex",
}

#: Label prefixes the external publication engine's pre-render citation check
#: treats as cross-references rather than bibliography keys. Anything outside
#: this set is reported as an undefined citation and the combined PDF is refused
#: before pandoc runs — a `rem:` label did exactly that and cost a render.
#:
#: The list is restated here on purpose. This repository cannot run that engine
#: (see STANDALONE.md), so the constraint is declared locally and checked
#: locally; the alternative is discovering it only in a checkout that has the
#: engine, which is precisely the coupling this project avoids.
RENDERER_ACCEPTED_PREFIXES: frozenset[str] = frozenset(
    {"sec", "fig", "tbl", "eq", "lst", "def", "prop", "inv", "conj", "alg", "thm"}
)

#: Titles the filter prints, used to catch a hand-written number in prose.
_KIND_TITLES = tuple(kind.capitalize() for kind in KIND_PREFIXES)
_HAND_NUMBER = re.compile(
    r"\b(?:" + "|".join(_KIND_TITLES) + r")s?\s+[0-9]+",
)

_FENCE = re.compile(r"^```", re.MULTILINE)
_DIV_OPEN = re.compile(r"^:::+\s*\{([^}]*)\}\s*$", re.MULTILINE)
_DIV_ANY = re.compile(r"^:::+", re.MULTILINE)
_CITATION = re.compile(r"\[@([A-Za-z][\w:.-]*)\]")
_LABEL = re.compile(r"^[a-z]+:[a-z0-9][a-z0-9-]*$")


def manuscript_sources() -> dict[str, str]:
    """Every manuscript markdown file, keyed by filename."""

    return {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted(MANUSCRIPT.glob("*.md"))
    }


def without_code_blocks(text: str) -> str:
    """Drop fenced code blocks, keeping line structure elsewhere intact."""

    kept: list[str] = []
    inside = False
    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            inside = not inside
            continue
        if not inside:
            kept.append(line)
    return "\n".join(kept)


def declared_blocks(sources: dict[str, str]) -> list[tuple[str, str, str]]:
    """Return ``(filename, kind class, label)`` for every formalism Div."""

    found: list[tuple[str, str, str]] = []
    for name, text in sources.items():
        for attrs in _DIV_OPEN.findall(without_code_blocks(text)):
            classes = [token[1:] for token in attrs.split() if token.startswith(".")]
            kinds = [cls for cls in classes if cls in KIND_PREFIXES]
            if not kinds:
                continue
            identifiers = [
                token[1:] for token in attrs.split() if token.startswith("#")
            ]
            label = identifiers[0] if identifiers else ""
            for kind in kinds:
                found.append((name, kind, label))
    return found


def block_defects(sources: dict[str, str]) -> list[str]:
    """Every formalism block that is unlabelled, mislabelled, or duplicated."""

    defects: list[str] = []
    seen: dict[str, str] = {}
    for name, kind, label in declared_blocks(sources):
        if not label:
            defects.append(f"{name}: a .{kind} block carries no label")
            continue
        if not _LABEL.match(label):
            defects.append(f"{name}: label {label!r} is not prefix:name")
            continue
        expected = KIND_PREFIXES[kind]
        if label.split(":", 1)[0] != expected:
            defects.append(
                f"{name}: .{kind} block labelled {label!r} should use "
                f"the {expected}: prefix"
            )
        if label in seen:
            defects.append(f"{name}: label {label!r} already declared in {seen[label]}")
        else:
            seen[label] = name
    return defects


def unbalanced_fences(sources: dict[str, str]) -> list[str]:
    """Files whose ``:::`` markers do not pair up."""

    unbalanced: list[str] = []
    for name, text in sources.items():
        markers = _DIV_ANY.findall(without_code_blocks(text))
        if len(markers) % 2:
            unbalanced.append(f"{name}: {len(markers)} ::: markers do not pair")
    return unbalanced


def formalism_references(sources: dict[str, str]) -> list[tuple[str, str]]:
    """``(filename, id)`` for every citation whose prefix a formalism block uses.

    This mirrors the filter's own rule: a citation belongs to the formalism
    vocabulary when its prefix is one the document actually declares. A
    bibliography key of the ordinary ``author:year`` shape is left alone.
    """

    prefixes = {
        label.split(":", 1)[0]
        for _name, _kind, label in declared_blocks(sources)
        if ":" in label
    }
    found: list[tuple[str, str]] = []
    for name, text in sources.items():
        for identifier in _CITATION.findall(without_code_blocks(text)):
            if ":" in identifier and identifier.split(":", 1)[0] in prefixes:
                found.append((name, identifier))
    return found


def unresolved_references(sources: dict[str, str]) -> list[str]:
    """Formalism references naming a label no block in the manuscript declares."""

    declared = {label for _name, _kind, label in declared_blocks(sources) if label}
    return [
        f"{name}: [@{identifier}] names no declared block"
        for name, identifier in formalism_references(sources)
        if identifier not in declared
    ]


def hand_written_numbers(sources: dict[str, str]) -> list[str]:
    """Every ``Definition 3``-style literal in prose outside a fenced block."""

    found: list[str] = []
    for name, text in sources.items():
        for lineno, line in enumerate(without_code_blocks(text).splitlines(), start=1):
            match = _HAND_NUMBER.search(line)
            if match:
                found.append(f"{name}:{lineno}: hand-written {match.group(0)!r}")
    return found


# --- the real manuscript ------------------------------------------------------


def test_the_formalism_scan_is_not_vacuous() -> None:
    """A sweep that found no blocks would make every check below meaningless."""

    sources = manuscript_sources()
    assert len(sources) >= 10, sorted(sources)
    blocks = declared_blocks(sources)
    assert len(blocks) >= 20, len(blocks)
    kinds = {kind for _name, kind, _label in blocks}
    assert {"definition", "proposition"} <= kinds, kinds
    assert len(formalism_references(sources)) >= 10, formalism_references(sources)


def test_every_label_prefix_survives_the_renderer_citation_check() -> None:
    """A prefix outside the engine's list is refused before pandoc ever runs.

    Caught the hard way: a `.remark` block labelled `rem:global-local` rendered
    fine locally and failed the combined PDF with "undefined citation key". The
    block became a proposition; this check keeps the next one from repeating it.
    """

    sources = manuscript_sources()
    prefixes = {
        label.split(":", 1)[0]
        for _name, _kind, label in declared_blocks(sources)
        if ":" in label
    }
    assert prefixes, "no labelled block would make this vacuous"
    assert prefixes <= RENDERER_ACCEPTED_PREFIXES, sorted(
        prefixes - RENDERER_ACCEPTED_PREFIXES
    )
    # The same constraint binds references, which are what the engine scans.
    reference_prefixes = {
        identifier.split(":", 1)[0]
        for _name, identifier in formalism_references(sources)
    }
    assert reference_prefixes <= RENDERER_ACCEPTED_PREFIXES, sorted(
        reference_prefixes - RENDERER_ACCEPTED_PREFIXES
    )


def test_the_renderer_prefix_check_can_fail() -> None:
    """Positive control: a `rem:` label is exactly what the engine refuses."""

    planted = {"planted.md": "::: {.remark #rem:aside}\nAn aside.\n:::\n"}
    prefixes = {
        label.split(":", 1)[0]
        for _name, _kind, label in declared_blocks(planted)
        if ":" in label
    }
    assert prefixes == {"rem"}
    assert not prefixes <= RENDERER_ACCEPTED_PREFIXES


def test_every_formalism_block_carries_a_well_formed_unique_label() -> None:
    assert block_defects(manuscript_sources()) == []


def test_every_formalism_div_is_closed() -> None:
    assert unbalanced_fences(manuscript_sources()) == []


def test_every_formalism_reference_resolves_to_a_declared_block() -> None:
    assert unresolved_references(manuscript_sources()) == []


def test_no_manuscript_file_writes_a_block_number_by_hand() -> None:
    assert hand_written_numbers(manuscript_sources()) == []


def test_the_binding_tables_reference_every_declared_block() -> None:
    """A labelled block nothing points at is a claim with no reader path to it.

    The formalism section's two tables are the reader's index from claim to
    failing test. A block that never appears in a reference is either unused or
    unbound; either way the table has drifted from the section.
    """

    sources = manuscript_sources()
    declared = {label for _name, _kind, label in declared_blocks(sources)}
    referenced = {identifier for _name, identifier in formalism_references(sources)}
    assert declared - referenced == set(), sorted(declared - referenced)


# --- positive controls: each checker is shown rejecting a planted violation ---


def test_the_label_check_rejects_an_unlabelled_and_a_mislabelled_block() -> None:
    planted = {
        "planted.md": (
            "::: {.definition}\nNo label at all.\n:::\n\n"
            "::: {.proposition #def:wrong-prefix}\nWrong prefix.\n:::\n\n"
            "::: {.definition #NotALabel}\nNot prefix:name.\n:::\n"
        )
    }
    defects = block_defects(planted)
    assert len(defects) == 3, defects
    assert "carries no label" in defects[0]
    assert "should use the prop: prefix" in defects[1]
    assert "is not prefix:name" in defects[2]


def test_the_label_check_rejects_a_duplicate_label() -> None:
    planted = {
        "a.md": "::: {.definition #def:twice}\nOne.\n:::\n",
        "b.md": "::: {.definition #def:twice}\nTwo.\n:::\n",
    }
    defects = block_defects(planted)
    assert len(defects) == 1
    assert "already declared in a.md" in defects[0]


def test_the_reference_check_rejects_a_reference_to_no_block() -> None:
    planted = {
        "planted.md": (
            "::: {.proposition #prop:real}\nReal.\n:::\n\n"
            "See [@prop:real] and [@prop:typo], and cite [@popper1959logic].\n"
        )
    }
    unresolved = unresolved_references(planted)
    assert unresolved == ["planted.md: [@prop:typo] names no declared block"]
    # The bibliography key is not claimed by the formalism vocabulary.
    assert [identifier for _name, identifier in formalism_references(planted)] == [
        "prop:real",
        "prop:typo",
    ]


def test_the_hand_number_check_rejects_prose_and_spares_code() -> None:
    planted = {
        "planted.md": (
            "Proposition 6 pins this boundary, as do Definitions 2 and 3.\n\n"
            "```text\nDefinition 9 lives in a code block and is not prose.\n```\n\n"
            "The prop:ladder label carries no number.\n"
        )
    }
    found = hand_written_numbers(planted)
    assert len(found) == 1, found
    assert "'Proposition 6'" in found[0]
    # And the same text with the numbers removed is accepted.
    assert (
        hand_written_numbers(
            {"planted.md": "[@prop:strict-staleness] pins this boundary.\n"}
        )
        == []
    )


def test_the_fence_check_rejects_an_unclosed_div() -> None:
    planted = {"planted.md": "::: {.definition #def:open}\nNever closed.\n"}
    assert unbalanced_fences(planted) == ["planted.md: 1 ::: markers do not pair"]


def test_the_code_block_stripper_keeps_prose_and_drops_fenced_text() -> None:
    """Positive control for the stripper the other checks depend on."""

    text = "before\n```bash\nfenced\n```\nafter\n"
    stripped = without_code_blocks(text)
    assert "fenced" not in stripped
    assert "before" in stripped and "after" in stripped
